apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tag1: value1
    tag2: value2
    tag3: value3
    tag4: value4
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
